// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BMc0tFQLkRSc2OuRj0MRolDwngoQCMQ',
    appId: '1:27099870753:web:53a44c3e944d5ba4519560',
    messagingSenderId: '27099870753',
    projectId: 'esp8266-flutter-app',
    authDomain: 'esp8266-flutter-app.firebaseapp.com',
    databaseURL: 'https://esp8266-flutter-app-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-flutter-app.firebasestorage.app',
    measurementId: 'G-X9Q25QJDG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYLUONPdFLlc2cQap-2LEq5nh51POzqvo',
    appId: '1:27099870753:android:ab9cd70a8bba7d0c519560',
    messagingSenderId: '27099870753',
    projectId: 'esp8266-flutter-app',
    databaseURL: 'https://esp8266-flutter-app-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqMJkWC70553cJlSRac7kR0xhbqNg6n8I',
    appId: '1:27099870753:ios:8cdf7cdfeb7caff7519560',
    messagingSenderId: '27099870753',
    projectId: 'esp8266-flutter-app',
    databaseURL: 'https://esp8266-flutter-app-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-flutter-app.firebasestorage.app',
    androidClientId: '27099870753-ti1j97585q6hpu4tks5d3h7s6v5kkb5d.apps.googleusercontent.com',
    iosClientId: '27099870753-iafi4n21no4kfeum97lhh52a1ibgbd16.apps.googleusercontent.com',
    iosBundleId: 'com.example.esp8266Project',
  );
}
